/*
 * Math710Form.java
 *
 * Created on August 20, 2006, 3:33 AM
 */

package math710;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author  mike
 */
public class Math710Form extends javax.swing.JFrame {
    
    private Hashtable<String, Integer> corpusDirs = new Hashtable<String, Integer>();
    private String stopList = null;
    private String serializedStorage = null;
    
    /** Creates new form Math710Form */
    public Math710Form() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        termInclusion = new javax.swing.ButtonGroup();
        corpusPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultListModel corpusDirectoriesListModel = new DefaultListModel();
        corpusDirectories = new JList(corpusDirectoriesListModel);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        termInclusionUseAll = new javax.swing.JRadioButton();
        termInclusionUsePartial = new javax.swing.JRadioButton();
        numTermsToUse = new javax.swing.JTextField();
        cmbStopListSelect = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbStopListSelect1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        corpusDirectories.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(corpusDirectories);

        jButton1.setText("Add Additional Directories To Corpus");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Remove Selected Directories From Corpus");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jButton1)
                        .add(58, 58, 58)
                        .add(jButton2)
                        .add(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(44, 44, 44)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(83, 83, 83)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        corpusPanel.addTab("Select Corpus", jPanel1);

        jLabel1.setText("Shall I use all terms?");

        jLabel2.setText("What number of highest variance terms shall I use?");

        termInclusion.add(termInclusionUseAll);
        termInclusionUseAll.setText("Use all Terms");
        termInclusionUseAll.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        termInclusionUseAll.setMargin(new java.awt.Insets(0, 0, 0, 0));

        termInclusion.add(termInclusionUsePartial);
        termInclusionUsePartial.setText("Use partial terms");
        termInclusionUsePartial.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        termInclusionUsePartial.setMargin(new java.awt.Insets(0, 0, 0, 0));
        termInclusionUsePartial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                termInclusionUsePartialStateChanged(evt);
            }
        });

        numTermsToUse.setEditable(false);

        cmbStopListSelect.setText("Select Stop List");
        cmbStopListSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStopListSelectMouseClicked(evt);
            }
        });

        jLabel3.setText("Please select the stop list you wish to use:");

        jButton4.setText("Perform Initial Document Parsing");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Build Model Using Settings Above");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel5.setText("Where shall I store serialized files:");

        cmbStopListSelect1.setText("Select serialized file location");
        cmbStopListSelect1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStopListSelect1MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jButton4)
                    .add(jLabel5)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 107, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton5)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, cmbStopListSelect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, numTermsToUse)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(termInclusionUseAll)
                            .add(24, 24, 24)
                            .add(termInclusionUsePartial)))
                    .add(cmbStopListSelect1))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(termInclusionUseAll)
                    .add(termInclusionUsePartial))
                .add(15, 15, 15)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(numTermsToUse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmbStopListSelect)
                    .add(jLabel3))
                .add(15, 15, 15)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel5)
                        .add(cmbStopListSelect1)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 166, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton4)
                    .add(jButton5))
                .add(29, 29, 29))
        );
        corpusPanel.addTab("Preprocess Corpus", jPanel2);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 594, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 372, Short.MAX_VALUE)
        );
        corpusPanel.addTab("Cluster Corpus", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(corpusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 599, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(corpusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 397, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectSerializedFileLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSelectSerializedFileLocationMouseClicked
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(fc.DIRECTORIES_ONLY);
        if(fc.showOpenDialog(Math710Form.this) == JFileChooser.APPROVE_OPTION){
            this.serializedStorage = fc.getSelectedFile().getAbsolutePath();
            this.currentStorageDirectory.setText(this.serializedStorage);
        }
    }//GEN-LAST:event_cmbSelectSerializedFileLocationMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // use n-variance terms, incorporate phase2, serialize BKM
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // Serialize documents... serialize BKM before phase 2.
    }//GEN-LAST:event_jButton4MouseClicked

    private void cmbStopListSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStopListSelectMouseClicked
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(fc.DIRECTORIES_ONLY);
        if(fc.showOpenDialog(Math710Form.this) == JFileChooser.APPROVE_OPTION){
            this.stopList = fc.getSelectedFile().getAbsolutePath();
            this.currentStopList.setText(this.stopList);
        }
    }//GEN-LAST:event_cmbStopListSelectMouseClicked

    private void termInclusionUsePartialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_termInclusionUsePartialStateChanged
        if(termInclusionUsePartial.isSelected() == true){
            numTermsToUse.setEditable(true);
        } else {
            numTermsToUse.setEditable(false);
            numTermsToUse.setText("");
        }
    }//GEN-LAST:event_termInclusionUsePartialStateChanged
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(fc.DIRECTORIES_ONLY);
        if(fc.showOpenDialog(Math710Form.this) == JFileChooser.APPROVE_OPTION){
            DefaultListModel corpusDirectoriesListModel = (DefaultListModel)corpusDirectories.getModel();
            String path = fc.getSelectedFile().getAbsolutePath();
            if(this.corpusDirs.get(path) != null){
                
            } else {
                this.corpusDirs.put(path, 1);
                corpusDirectoriesListModel.add(0, path);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Math710Form().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbSelectSerializedFileLocation;
    private javax.swing.JButton cmbStopListSelect;
    private javax.swing.JList corpusDirectories;
    private javax.swing.JTabbedPane corpusPanel;
    private javax.swing.JTextField currentStorageDirectory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numTermsToUse;
    private javax.swing.ButtonGroup termInclusion;
    private javax.swing.JRadioButton termInclusionUseAll;
    private javax.swing.JRadioButton termInclusionUsePartial;
    // End of variables declaration//GEN-END:variables
    
}
